language: python
python:
  - "3.6"
  - "3.7"
install: pip install mypy flake8
script:
  - mypy refract tests
  - python -m unittest discover -v
  - flake8 refract tests --ignore=W503 --max-line-length=100
