language: python
python:
  - "3.6"
  - "3.7"
# Enable Python 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install: pip install mypy flake8
script:
  - mypy refract tests
  - python -m unittest discover -v
  - flake8 refract tests --ignore=W503 --max-line-length=100
